AllCops:
  TargetRubyVersion: 2.5.3

Style/FrozenStringLiteralComment:
  Description: >-
    Add the frozen_string_literal comment to the top of files
    to help transition from Ruby 2.3.0 to Ruby 3.0.
  EnforcedStyle: never
